function quoteGenerator() {

    var quotes = [
        "WOO!",
        "YEAH!",
        "WOO! YEAH!",
        "Boing!",
        "Ok!",
        "There you are!",
        "We've updated our privacy policy.",
        "We've updated our terms of service.",
        "I don't get it",
        "The best in town!",
        "Beware, I live!",
        "how many times have you refreshed this jesus christ man",
        "what's it gonna be? Huh? Huh?",
        "Oh Eh Oh Ah Ah Ting Tang Walla Walla Bing Bang",
        "All the people rest at the Moon's request",
        "I got a girlfriend that's better than that",
        "You may find yourself in another part of the world",
        "This is not my beautiful wife",
        "Water in a well fell down",
        "Today is not my day",
        "Tomorrow will be my day",
        "It can only be found now",
        "I'll walk into the landscape and I won't come back",
        "You gotta dance",
        "You gotta dance, you know this is a dance audition?",
        "I wanna dance, wanna fly, want a unicorn!",
        "Bring me fun",
        "She's terminal blue",
        "Decimator!",
        "Into oblivion!",
        "Shine on!",
        "I am the exit",
        "Nothing can stop me now",
        "If there is a hell I'll see you there",
        "it's the nature of my circuitry",
        "I wanna know everything",
        "I wanna do something that matters",
        "it's completely dark when I close my eyes!",
        "I'll crypto-freeze you together with some English beef!!",
        "IT'S FREE",
        "A good day to blow stuff up!",
        "Don't bring a knife to a rocket launcher fight!",
        "Hello! Today is a wonderful day.",
        "pl0x",
        "friend",
        "Soup!",
        "Juice!",
        "ROBLOX brings you Pants",
        "Pants and Pants and Pants and Pants and Shirts",
        "and Pants and Shirts and Shirts and Pants and Shirts",
        "I see you - friend!",
        "I hug people for all eternity!",
        "When will you learn?",
        "Hehehehehee!",
        "Oh, hi! Welcome to my website!",
        "WOW! YOU EXIST!",
        "I HEAR CODE THAT BAD",
        "WOW!",
        "ohhhhhhhhhhhhhhhhhhhh",
        "The Quick Brown Fox Jumps Over The Lazy Dog",
        "in Life, the Sensuous Dream",
        "in Limbo, the Silent Dream",
        "in Logic, the Symbolic Dream",
        "in Laughter, the Spiritual Dream", 
        "in Lunacy, the Savage Dream", 
        "in Leisure, the Sonorous Dream",
        "in Linking, the Sapient Dream",
        "Dream on!",
        "9",
        "24",
        "42",
        "1337",
    ];

    document.getElementById("quote").innerHTML = quotes[Math.floor(Math.random() * quotes.length)];
    }

quoteGenerator();