function quoteGenerator() {

    var quotes = [
        "pl0x",
        "IT'S FREE",
        "WOO!",
        "YEAH!",
        "WOO! YEAH!",
        "Boing!",
        "Ok!",
        "How many times have you refreshed this jesus christ man",
        "what's it gonna be? Huh? Huh?",
        "Oh Eh Oh Ah Ah Ting Tang Walla Walla Bing Bang",
        "all the people rest at the Moon's request",
        "I got a girlfriend that's better than that",
        "this is not my beautiful wife",
        "water in a well fell down",
        "today is not my day",
        "tomorrow will be my day",
        "you gotta dance",
        "I wanna dance, wanna fly, want a unicorn!",
        "bring me fun",
        "she's terminal blue",
        "decimator!",
        "into oblivion!",
        "shine on!",
        "it's the nature of my circuitry",
        "if there is a hell I'll see you there",
        "it's completely dark when I close my eyes!",
        "I'll crypto-freeze you together with some English beef!!",
        "I don't get it",
        "Oh, hi! Welcome to my website!",
        "I HEAR CODE THAT BAD",
        "WOW!",
        "ohhhhhhhhhhhhhhhhhhhh",
        "The Quick Brown Fox Jumps Over The Lazy Dog",
        "in Life, the Sensuous Dream",
        "in Limbo, the Silent Dream",
        "in Logic, the Symbolic Dream",
        "in Laughter, the Spiritual Dream", 
        "in Lunacy, the Savage Dream", 
        "in Leisure, the Sonorous Dream",
        "in Linking, the Sapient Dream",
        "Dream on!",
        "9",
        "24",
        "42",
        "1337",
    ];

    document.getElementById("quote").innerHTML = quotes[Math.floor(Math.random() * quotes.length)];
    }

quoteGenerator();