function quoteGenerator() {

    var quotes = [
        "<a href='https://file.garden/ZX_65G2nsi-rTDmw/pearkit.png' target='_href'>DO NOT CLICK ON ME</a>",
        "<span aria-hidden='true'>૮( ^_^ )১</span>",
        "<span aria-hidden='true'>૮( -_- )১ zzz..</span>",
        "<span aria-hidden='true'>ᓚᘏᗢ</span>",
        "<span aria-hidden='true'>/ᐠ - ˕ -マⳊ</span>",
        "<span aria-hidden='true'>@y</span>",
        "<span aria-hidden='true'>▀▄▀</span>",
        "WOO!",
        "YEAH!",
        "WOO! YEAH!",
        "Boing!",
        "Ok!",
        "Welcome to the fifth dimension!",
        "I split the atom",
        "I play computer",
        "There you are!",
        "We've updated our privacy policy.",
        "We've updated our terms of service.",
        "I don't get it",
        "The best in town!",
        "When you're not looking at this website it doesn't exist",
        "Beware, I live!",
        "how many times have you refreshed this jesus christ man",
        "what's it gonna be? Huh? Huh?",
        "Oh Eh Oh Ah Ah Ting Tang Walla Walla Bing Bang",
        "All the people rest at the Moon's request",
        "You are one ant",
        "I got a girlfriend that's better than that",
        "You may find yourself in another part of the world",
        "This is not my beautiful wife",
        "Water in a well fell down",
        "Today is not my day",
        "Tomorrow will be my day",
        "It can only be found now",
        "I'll walk into the landscape and I won't come back",
        "You gotta dance",
        "You gotta dance, you know this is a dance audition?",
        "I wanna dance, wanna fly, want a unicorn!",
        "Bring me fun",
        "Stop making that big face!",
        "She's terminal blue",
        "Decimator!",
        "Into oblivion!",
        "Shine on!",
        "I am the exit",
        "Nothing can stop me now",
        "If there is a hell I'll see you there",
        "it's the nature of my circuitry",
        "I wanna know everything",
        "I wanna do something that matters",
        "it's completely dark when I close my eyes!",
        "I'll crypto-freeze you together with some English beef!!",
        "IT'S FREE",
        "A good day to blow stuff up!",
        "Don't bring a knife to a rocket launcher fight!",
        "Hello! Today is a wonderful day.",
        "I'm not gonna sugarcoat it.",
        "Toasted!",
        "pl0x",
        "friend",
        "Soup!",
        "Juice!",
        "NAO",
        "Yease",
        "Who is that guy, anyway? An Identity Fraud?",
        "My Nice Mother Long Pond Lots Kill Jack Key",
        "The New Jersey Has The Long President The New President",
        "FROSPITALITY IS REAL 2401",
        "Dearest of all my friends",
        "Damn the world, damn you",
        "Each day better than the last",
        "I'm happily engaged... to Pie Hiking. And I have someone, too.",
        "This guy won't stop talking about seals...",
        "These are DEFINITELY not fish.",
        "Mmm, Chavez.",
        "PIZZA!",
        "Mmm, chezburger!",
        "Can I has chezburger please?",
        "ROBLOX brings you Pants",
        "Pants and Pants and Pants and Pants and Shirts",
        "and Pants and Shirts and Shirts and Pants and Shirts",
        "I see you - friend!",
        "I hug people for all eternity!",
        "When will you learn?",
        "Hehehehehee!",
        "Oh, hi! Welcome to my website!",
        "WOW! YOU EXIST!",
        "I HEAR CODE THAT BAD",
        "WOW!",
        "ohhhhhhhhhhhhhhhhhhhh",
        "The Quick Brown Fox Jumps Over The Lazy Dog",
        "in Life, the Sensuous Dream",
        "in Limbo, the Silent Dream",
        "in Logic, the Symbolic Dream",
        "in Laughter, the Spiritual Dream", 
        "in Lunacy, the Savage Dream", 
        "in Leisure, the Sonorous Dream",
        "in Linking, the Sapient Dream",
        "Dream on!",
        "Working... please wait...",
        "9",
        "24",
        "42",
        "1337",
    ];

    document.getElementById("quote").innerHTML = quotes[Math.floor(Math.random() * quotes.length)];
    }

quoteGenerator();